# Hyprland Autostart Configuration
exec-once = hyprpaper
exec-once = hypridle
exec-once = nuit-aur-install
exec-once = sleep 1 && nuit-theme-bg-next --random
exec-once = /usr/lib/hyprpolkitagent/hyprpolkitagent
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
