[options]
RootDir          = /install/
CacheDir         = /var/cache/pacman/pkg/
GPGDir           = /etc/pacman.d/gnupg/
HookDir          = /etc/pacman.d/hooks/
Architecture     = x86_64
Color
CheckSpace
SigLevel    = Required DatabaseOptional
LocalFileSigLevel = Optional

[core]
Include = /etc/pacman.d/mirrorlist

[extra]
Include = /etc/pacman.d/mirrorlist

[community]
Include = /etc/pacman.d/mirrorlist
